# docker-compose-dev.yml
version: '3.5'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.ui.dev
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./:/app/
      - /app/node_modules
      - ./data-volume:/app/data
    stdin_open: true
    tty: true
    networks:
    - default
    hostname: frontend
    container_name: frontend

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.bondai.dev
    #restart: always
    working_dir: /agent-volume
    env_file:
      - ../.env
    ports:
      - "2663:2663"
    volumes:
      - ./agent-volume:/agent-volume
    environment:
      - FLASK_ENV=development
    command: ["bondai", "--server", "2663", "--enable-prompt-logging", "--enable-dangerous"]
    networks:
    - default
    hostname: backend
    container_name: backend